/**
 * @fileoverview
 * @enhanceable
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

goog.provide('proto.KBVector4');

goog.require('jspb.Message');


/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.KBVector4 = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.KBVector4, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.KBVector4.displayName = 'proto.KBVector4';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.KBVector4.prototype.toObject = function(opt_includeInstance) {
  return proto.KBVector4.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.KBVector4} msg The msg instance to transform.
 * @return {!Object}
 */
proto.KBVector4.toObject = function(includeInstance, msg) {
  var f, obj = {
    x: msg.getX(),
    y: msg.getY(),
    z: msg.getZ(),
    w: msg.getW()
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg
  }
  return obj;
};
}


/**
 * Creates a deep clone of this proto. No data is shared with the original.
 * @return {!proto.KBVector4} The clone.
 */
proto.KBVector4.prototype.cloneMessage = function() {
  return /** @type {!proto.KBVector4} */ (jspb.Message.cloneMessage(this));
};


/**
 * optional float x = 1;
 * @return {number}
 */
proto.KBVector4.prototype.getX = function() {
  return /** @type {number} */ (jspb.Message.getFieldProto3(this, 1, 0));
};


/** @param {number} value  */
proto.KBVector4.prototype.setX = function(value) {
  jspb.Message.setField(this, 1, value);
};


/**
 * optional float y = 2;
 * @return {number}
 */
proto.KBVector4.prototype.getY = function() {
  return /** @type {number} */ (jspb.Message.getFieldProto3(this, 2, 0));
};


/** @param {number} value  */
proto.KBVector4.prototype.setY = function(value) {
  jspb.Message.setField(this, 2, value);
};


/**
 * optional float z = 3;
 * @return {number}
 */
proto.KBVector4.prototype.getZ = function() {
  return /** @type {number} */ (jspb.Message.getFieldProto3(this, 3, 0));
};


/** @param {number} value  */
proto.KBVector4.prototype.setZ = function(value) {
  jspb.Message.setField(this, 3, value);
};


/**
 * optional float w = 4;
 * @return {number}
 */
proto.KBVector4.prototype.getW = function() {
  return /** @type {number} */ (jspb.Message.getFieldProto3(this, 4, 0));
};


/** @param {number} value  */
proto.KBVector4.prototype.setW = function(value) {
  jspb.Message.setField(this, 4, value);
};


