/**
 * @fileoverview
 * @enhanceable
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

goog.provide('proto.KBJoint');
goog.provide('proto.KBJoint.KBCameraSpacePoint');
goog.provide('proto.KBJoint.KBTrackingState');

goog.require('jspb.Message');

goog.forwardDeclare('proto.KBJointType');

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.KBJoint = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.KBJoint, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.KBJoint.displayName = 'proto.KBJoint';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.KBJoint.prototype.toObject = function(opt_includeInstance) {
  return proto.KBJoint.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.KBJoint} msg The msg instance to transform.
 * @return {!Object}
 */
proto.KBJoint.toObject = function(includeInstance, msg) {
  var f, obj = {
    type: msg.getType(),
    position: (f = msg.getPosition()) && proto.KBJoint.KBCameraSpacePoint.toObject(includeInstance, f),
    state: msg.getState()
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg
  }
  return obj;
};
}


/**
 * Creates a deep clone of this proto. No data is shared with the original.
 * @return {!proto.KBJoint} The clone.
 */
proto.KBJoint.prototype.cloneMessage = function() {
  return /** @type {!proto.KBJoint} */ (jspb.Message.cloneMessage(this));
};


/**
 * optional KBJointType type = 1;
 * @return {!proto.KBJointType}
 */
proto.KBJoint.prototype.getType = function() {
  return /** @type {!proto.KBJointType} */ (jspb.Message.getFieldProto3(this, 1, 0));
};


/** @param {!proto.KBJointType} value  */
proto.KBJoint.prototype.setType = function(value) {
  jspb.Message.setField(this, 1, value);
};


/**
 * optional KBCameraSpacePoint position = 2;
 * @return {proto.KBJoint.KBCameraSpacePoint}
 */
proto.KBJoint.prototype.getPosition = function() {
  return /** @type{proto.KBJoint.KBCameraSpacePoint} */ (
    jspb.Message.getWrapperField(this, proto.KBJoint.KBCameraSpacePoint, 2));
};


/** @param {proto.KBJoint.KBCameraSpacePoint|undefined} value  */
proto.KBJoint.prototype.setPosition = function(value) {
  jspb.Message.setWrapperField(this, 2, value);
};


proto.KBJoint.prototype.clearPosition = function() {
  this.setPosition(undefined);
};


/**
 * optional KBTrackingState state = 4;
 * @return {!proto.KBJoint.KBTrackingState}
 */
proto.KBJoint.prototype.getState = function() {
  return /** @type {!proto.KBJoint.KBTrackingState} */ (jspb.Message.getFieldProto3(this, 4, 0));
};


/** @param {!proto.KBJoint.KBTrackingState} value  */
proto.KBJoint.prototype.setState = function(value) {
  jspb.Message.setField(this, 4, value);
};


/**
 * @enum {number}
 */
proto.KBJoint.KBTrackingState = {
  NOT_TRACKED: 0,
  INFERRED: 1,
  TRACKED: 2
};


/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.KBJoint.KBCameraSpacePoint = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.KBJoint.KBCameraSpacePoint, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.KBJoint.KBCameraSpacePoint.displayName = 'proto.KBJoint.KBCameraSpacePoint';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.KBJoint.KBCameraSpacePoint.prototype.toObject = function(opt_includeInstance) {
  return proto.KBJoint.KBCameraSpacePoint.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.KBJoint.KBCameraSpacePoint} msg The msg instance to transform.
 * @return {!Object}
 */
proto.KBJoint.KBCameraSpacePoint.toObject = function(includeInstance, msg) {
  var f, obj = {
    x: msg.getX(),
    y: msg.getY(),
    z: msg.getZ()
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg
  }
  return obj;
};
}


/**
 * Creates a deep clone of this proto. No data is shared with the original.
 * @return {!proto.KBJoint.KBCameraSpacePoint} The clone.
 */
proto.KBJoint.KBCameraSpacePoint.prototype.cloneMessage = function() {
  return /** @type {!proto.KBJoint.KBCameraSpacePoint} */ (jspb.Message.cloneMessage(this));
};


/**
 * optional float x = 1;
 * @return {number}
 */
proto.KBJoint.KBCameraSpacePoint.prototype.getX = function() {
  return /** @type {number} */ (jspb.Message.getFieldProto3(this, 1, 0));
};


/** @param {number} value  */
proto.KBJoint.KBCameraSpacePoint.prototype.setX = function(value) {
  jspb.Message.setField(this, 1, value);
};


/**
 * optional float y = 2;
 * @return {number}
 */
proto.KBJoint.KBCameraSpacePoint.prototype.getY = function() {
  return /** @type {number} */ (jspb.Message.getFieldProto3(this, 2, 0));
};


/** @param {number} value  */
proto.KBJoint.KBCameraSpacePoint.prototype.setY = function(value) {
  jspb.Message.setField(this, 2, value);
};


/**
 * optional float z = 3;
 * @return {number}
 */
proto.KBJoint.KBCameraSpacePoint.prototype.getZ = function() {
  return /** @type {number} */ (jspb.Message.getFieldProto3(this, 3, 0));
};


/** @param {number} value  */
proto.KBJoint.KBCameraSpacePoint.prototype.setZ = function(value) {
  jspb.Message.setField(this, 3, value);
};


